package com.sg.gate.musicserver.dao;

import com.sg.gate.musicserver.domain.ListSong;
import com.sg.gate.musicserver.domain.ListSongExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ListSongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    long countByExample(ListSongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    int deleteByExample(ListSongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    int insert(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    int insertSelective(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    List<ListSong> selectByExample(ListSongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    ListSong selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    int updateByExampleSelective(@Param("record") ListSong record, @Param("example") ListSongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    int updateByExample(@Param("record") ListSong record, @Param("example") ListSongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    int updateByPrimaryKeySelective(ListSong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_song
     *
     * @mbg.generated Tue Apr 12 19:33:01 CST 2022
     */
    int updateByPrimaryKey(ListSong record);
}