package com.sg.gate.musicserver.dao;

import com.sg.gate.musicserver.domain.Rank;
import com.sg.gate.musicserver.domain.RankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    long countByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    int deleteByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    int insert(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    int insertSelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    List<Rank> selectByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    Rank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    int updateByExampleSelective(@Param("record") Rank record, @Param("example") RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    int updateByExample(@Param("record") Rank record, @Param("example") RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    int updateByPrimaryKeySelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    int updateByPrimaryKey(Rank record);

    //  查总分
    int selectScoreSum(Integer songListId);

    //    查总评分人数
    int selectRankNum(Integer songListId);
}