package com.sg.gate.musicserver.dao;

import com.sg.gate.musicserver.domain.Song;
import com.sg.gate.musicserver.domain.SongExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    long countByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int deleteByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int insertSelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    List<Song> selectByExampleWithBLOBs(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    List<Song> selectByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    Song selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByExampleSelective(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByExample(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByPrimaryKeySelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByPrimaryKey(Song record);
}