package com.sg.gate.musicserver.dao;

import com.sg.gate.musicserver.domain.SongList;
import com.sg.gate.musicserver.domain.SongListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SongListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    long countByExample(SongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int deleteByExample(SongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int insert(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int insertSelective(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    List<SongList> selectByExample(SongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    SongList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByExampleSelective(@Param("record") SongList record, @Param("example") SongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByExample(@Param("record") SongList record, @Param("example") SongListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByPrimaryKeySelective(SongList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list
     *
     * @mbg.generated Mon Apr 11 10:05:03 CST 2022
     */
    int updateByPrimaryKey(SongList record);
}