package com.sg.gate.musicserver.domain;

import java.io.Serializable;
import java.util.Date;

public class Collect implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.user_id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.type
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    private Boolean type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.song_id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    private Integer songId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.song_list_id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    private Integer songListId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.create_time
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.id
     *
     * @return the value of collect.id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.id
     *
     * @param id the value for collect.id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.user_id
     *
     * @return the value of collect.user_id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.user_id
     *
     * @param userId the value for collect.user_id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.type
     *
     * @return the value of collect.type
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.type
     *
     * @param type the value for collect.type
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.song_id
     *
     * @return the value of collect.song_id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public Integer getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.song_id
     *
     * @param songId the value for collect.song_id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public void setSongId(Integer songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.song_list_id
     *
     * @return the value of collect.song_list_id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public Integer getSongListId() {
        return songListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.song_list_id
     *
     * @param songListId the value for collect.song_list_id
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public void setSongListId(Integer songListId) {
        this.songListId = songListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.create_time
     *
     * @return the value of collect.create_time
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.create_time
     *
     * @param createTime the value for collect.create_time
     *
     * @mbg.generated Wed Apr 13 17:08:39 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}