package com.sg.gate.musicserver.domain;

import java.io.Serializable;
import java.util.Date;

public class Consumer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.id
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.username
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.password
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.sex
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.phone_num
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.email
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.birth
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.introduction
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.location
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.avator
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private String avator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.create_time
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.update_time
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.id
     *
     * @return the value of consumer.id
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.id
     *
     * @param id the value for consumer.id
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.username
     *
     * @return the value of consumer.username
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.username
     *
     * @param username the value for consumer.username
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.password
     *
     * @return the value of consumer.password
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.password
     *
     * @param password the value for consumer.password
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.sex
     *
     * @return the value of consumer.sex
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.sex
     *
     * @param sex the value for consumer.sex
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.phone_num
     *
     * @return the value of consumer.phone_num
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.phone_num
     *
     * @param phoneNum the value for consumer.phone_num
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.email
     *
     * @return the value of consumer.email
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.email
     *
     * @param email the value for consumer.email
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.birth
     *
     * @return the value of consumer.birth
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.birth
     *
     * @param birth the value for consumer.birth
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.introduction
     *
     * @return the value of consumer.introduction
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.introduction
     *
     * @param introduction the value for consumer.introduction
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.location
     *
     * @return the value of consumer.location
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.location
     *
     * @param location the value for consumer.location
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.avator
     *
     * @return the value of consumer.avator
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public String getAvator() {
        return avator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.avator
     *
     * @param avator the value for consumer.avator
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setAvator(String avator) {
        this.avator = avator == null ? null : avator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.create_time
     *
     * @return the value of consumer.create_time
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.create_time
     *
     * @param createTime the value for consumer.create_time
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.update_time
     *
     * @return the value of consumer.update_time
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.update_time
     *
     * @param updateTime the value for consumer.update_time
     *
     * @mbg.generated Wed Apr 13 16:28:56 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}