package com.sg.gate.musicserver.domain;

import java.io.Serializable;

public class Rank implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.id
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.song_list_id
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    private Integer songListId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.consumer_id
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    private Integer consumerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.score
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.id
     *
     * @return the value of rank.id
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.id
     *
     * @param id the value for rank.id
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.song_list_id
     *
     * @return the value of rank.song_list_id
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    public Integer getSongListId() {
        return songListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.song_list_id
     *
     * @param songListId the value for rank.song_list_id
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    public void setSongListId(Integer songListId) {
        this.songListId = songListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.consumer_id
     *
     * @return the value of rank.consumer_id
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    public Integer getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.consumer_id
     *
     * @param consumerId the value for rank.consumer_id
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    public void setConsumerId(Integer consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.score
     *
     * @return the value of rank.score
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.score
     *
     * @param score the value for rank.score
     *
     * @mbg.generated Fri Apr 15 21:23:54 CST 2022
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}